/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-22 14:19:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fundPaper_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/bootstrap.jsp", Long.valueOf(1603285194281L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1603373525155L));
    _jspx_dependants.put("/css.jsp", Long.valueOf(1603374784895L));
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1603325536783L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".greentext{\r\n");
      out.write("\tcolor:green;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".redtext{\r\n");
      out.write("\tcolor:red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".graytext{\r\n");
      out.write("\tcolor:gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".strongtext{\r\n");
      out.write("\tfont-weight:bolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bigtext{\r\n");
      out.write("\tfont-size:large;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thinth{\r\n");
      out.write("\tfont-weight:lighter;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fb-item{\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fb-item p{\r\n");
      out.write("\tmargin-block-start: 0em;\r\n");
      out.write("\tmargin-block-end: 0px;\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write(".addiv{\r\n");
      out.write("\tpadding:3px 5px;\r\n");
      out.write("\tmargin:0px 15px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".buybtn{\r\n");
      out.write("\tbackground-color:#ff631e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-footer{\r\n");
      out.write("\tpadding: 2px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row{\r\n");
      out.write("\tmargin:2px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rowbkgdiv{\r\n");
      out.write("\theight:200px;\r\n");
      out.write("\tbackground-image:url(img/fundbkg.jpg);\r\n");
      out.write("\tbackground-repeat:repeat-x;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".paperfig{\r\n");
      out.write("\tmargin:0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".breadcrumb{\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tmargin:0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr{\r\n");
      out.write("\tmargin:0px;\r\n");
      out.write("\tmargin-block-start: 0em;\r\n");
      out.write("    margin-block-end: 1.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fundPayTable{\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>大象基金_基金要闻</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("\t<a class=\"navbar-brand\" href=\"index.jsp\"><img src=\"img/elephant.png\"\r\n");
      out.write("\t\talt=\"\" width=\"22%\" height=\"22%\" style=\"margin-bottom:3px;margin-right:5px\">大象基金</a>\r\n");
      out.write("\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\tdata-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t</button>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\thref=\"index.jsp\">大盘指数 <span class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"fund.jsp\">基金产品</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"fundBuy.jsp\">基金导购</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"userInfo.jsp\">个人中心</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\"> Dropdown </a>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Action</a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link disabled\" href=\"#\">Disabled</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("\t\t\t<input class=\"form-control mr-sm-2\" type=\"search\"\r\n");
      out.write("\t\t\t\tplaceholder=\"请输入需要查找的内容\" aria-label=\"Search\">\r\n");
      out.write("\t\t\t<button class=\"btn\" type=\"submit\">\r\n");
      out.write("\t\t\t<img src=\"img/search.png\"></button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row rowbkgdiv\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 面包屑导航 -->\r\n");
      out.write("\t\t<nav aria-label=\"breadcrumb\">\r\n");
      out.write("\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t您所在位置 ：\r\n");
      out.write("\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"#\">大象基金</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"index.jsp\">大盘指数</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"breadcrumb-item active\" aria-current=\"page\">基金要闻</li>\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 文章标题 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<h3>A股三大指数缩量收跌：创业板指跌1% 可转债行情持续火爆</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 文章发表时间和文章来源 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<p class=\"graytext\">2020年10月22日 15:00 | 来源：东方财富研究中心</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 正文 ，包括图片和文字 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<p>　　A股三大指数今日延续弱势表现，最终集体收跌，其中沪指下跌0.38%，收报3312.50点；深成指下跌0.53%，收报13396.18点；创业板指跌幅达到1%，收报2673.59点。市场成交量萎缩，两市合计成交6637亿元，行业板块涨少跌多，酿酒板块领涨，疫苗板块领跌，券商板块尾盘异动。北向资金今日净卖出27.48亿元。</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<figure class=\"figure paperfig\">\r\n");
      out.write("\t\t\t\t<img src=\"img/paperPic/pp1.png\" class=\"figure-img img-fluid rounded\"\r\n");
      out.write("\t\t\t\t\talt=\"A generic square placeholder image with rounded corners in a figure.\">\r\n");
      out.write("\t\t\t\t<figcaption class=\"figure-caption text-right\">沪指下跌0.38%，收报3312.50点</figcaption>\r\n");
      out.write("\t\t\t</figure>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<figure class=\"figure paperfig\">\r\n");
      out.write("\t\t\t\t<img src=\"img/paperPic/pp2.png\" class=\"figure-img img-fluid rounded\"\r\n");
      out.write("\t\t\t\t\talt=\"A generic square placeholder image with rounded corners in a figure.\">\r\n");
      out.write("\t\t\t\t<figcaption class=\"figure-caption text-right\">深成指下跌0.53%，收报13396.18点</figcaption>\r\n");
      out.write("\t\t\t</figure>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<figure class=\"figure paperfig\">\r\n");
      out.write("\t\t\t\t<img src=\"img/paperPic/pp3.png\" class=\"figure-img img-fluid rounded\"\r\n");
      out.write("\t\t\t\t\talt=\"A generic square placeholder image with rounded corners in a figure.\">\r\n");
      out.write("\t\t\t\t<figcaption class=\"figure-caption text-right\">创业板指跌幅达到1%，收报2673.59点</figcaption>\r\n");
      out.write("\t\t\t</figure>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<p>　　值得注意的是，可转债市场延续了近期的火爆行情，正元转债收盘大涨176.41%，银河转债大涨73.22%，智能转债大涨31.30%。</p>\r\n");
      out.write("\t\t\t<p>　　对于后市大盘走向，机构纷纷发表看法。</p>\r\n");
      out.write("\t\t\t<p>　　林园投资董事长林园认为，大盘再创年内新高应该不难达到。因为现在距离新高也不是很远，这种概率还是挺大的。现在A股还在走牛市，往牛市方向发展。并没有对以前的判断做出调整，现在还是牛市初期。牛市初期的特征是板块轮动，就是有的板块有表现，有的板块歇一歇再表现。最近，有一些大市值的板块也出现上涨，能够轮动。这就说明A股目前是在牛市初期阶段运行的。在这期间，很大一部分股票都有机会，只是时间的问题。所以，如果主流产品能够不断地创出阶段性新高的话，股市整体是会创出新高的。</p>\r\n");
      out.write("\t\t\t<p>　　大成基金认为，四季度盈利上行更为确定，而流动性则处于从“货币信用弱双宽”到“稳货币稳信用”的过渡期，而盈利弱修复叠加流动性宽松正是对权益资产偏友好的组合。展望今年剩余时间，金融条件的宽松节奏与幅度决定A股走势，预计四季度A股以震荡为主，走“平台蓄势”路线。</p>\r\n");
      out.write("\t\t\t<p>　　银河基金对市场持相对中性的看法，认为虽然长逻辑上居民财富搬家的趋势或将仍然存在，但也看到市场主线面临估值回调、风险偏好回落的可能，同时股债相对性价比回归中性。接下来一段时间，市场核心聚焦于经济复苏预期提升后，市场结构是否会发生变化，同时谨防疫情二次复发以及外部因素对市场的冲击。</p>\r\n");
      out.write("\t\t\t<p>　　山西证券表示，目前市场上机构普遍对第四季度A股表现持乐观态度，从宏观经济角度上来看，复苏主线不改，中长期维持A股震荡向上走势判断。指数方面继续看好科创50指数中期表现，建议投资者在控制风险的前提下逢低介入。</p>\r\n");
      out.write("\t\t\t<p>　　招商基金表示，未来一个月，预计全球金融市场的波动率仍维持在高位。但考虑到国内经济持续复苏、金融地产等权重股估值仍在低位，A股预计仍以蓄势震荡为主。</p>\r\n");
      out.write("\t\t\t<p>　　天风证券指出，国内政策和基本面偏暖，指数逐步振荡修复，继续维持市场反弹的判断。短期资金对市场的扰动逐步消退，市场稳定性提升，龙头化依然是中长期资金聚焦的方向。受十四五规划预期以及行业基本面推动，顺周期制造业方向表现优异。消费电子关注下周及双十一的销售情况，其他个股机会围绕三季报展开。继续看好军工、光伏、新能源车、汽零、消费电子等。</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<img alt=\"ElephantmoneyFund\" src=\"img/elephantmoney.png\" style=\"display:block;margin:0% 0% 0% 80%;width:18%;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<p>上一篇：<a href=\"#\">可转债再现疯狂炒作 业内人士称行情或一周内结束</a></p>\r\n");
      out.write("\t\t\t<p>上一篇：<a href=\"#\">【今日盘点】创业板指跌1%，白酒主题基金逆势上涨；市场金针探底，A股的十字路口该怎么走？</a></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" id=\"footer\">\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<p class=\"lead\">联系邮箱 ： jacobon@foxmail.com</p>\r\n");
      out.write("\t<span class=\"text-muted\"><a href=\"https://github.com/ZUFEcsc\">GitHub</a>\r\n");
      out.write("\t\t| <a href=\"https://blog.csdn.net/qq_44702847\">CSDN</a></span>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
