/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-22 14:15:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fundPay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/bootstrap.jsp", Long.valueOf(1603285194281L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1603373525155L));
    _jspx_dependants.put("/css.jsp", Long.valueOf(1603374784895L));
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1603325536783L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".greentext{\r\n");
      out.write("\tcolor:green;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".redtext{\r\n");
      out.write("\tcolor:red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".graytext{\r\n");
      out.write("\tcolor:gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".strongtext{\r\n");
      out.write("\tfont-weight:bolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bigtext{\r\n");
      out.write("\tfont-size:large;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thinth{\r\n");
      out.write("\tfont-weight:lighter;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fb-item{\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fb-item p{\r\n");
      out.write("\tmargin-block-start: 0em;\r\n");
      out.write("\tmargin-block-end: 0px;\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write(".addiv{\r\n");
      out.write("\tpadding:3px 5px;\r\n");
      out.write("\tmargin:0px 15px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".buybtn{\r\n");
      out.write("\tbackground-color:#ff631e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-footer{\r\n");
      out.write("\tpadding: 2px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row{\r\n");
      out.write("\tmargin:2px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rowbkgdiv{\r\n");
      out.write("\theight:200px;\r\n");
      out.write("\tbackground-image:url(img/fundbkg.jpg);\r\n");
      out.write("\tbackground-repeat:repeat-x;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".paperfig{\r\n");
      out.write("\tmargin:0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".breadcrumb{\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tmargin:0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr{\r\n");
      out.write("\tmargin:0px;\r\n");
      out.write("\tmargin-block-start: 0em;\r\n");
      out.write("    margin-block-end: 1.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fundPayTable{\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>大象基金_基金购入</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("\t<a class=\"navbar-brand\" href=\"index.jsp\"><img src=\"img/elephant.png\"\r\n");
      out.write("\t\talt=\"\" width=\"22%\" height=\"22%\" style=\"margin-bottom:3px;margin-right:5px\">大象基金</a>\r\n");
      out.write("\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\tdata-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t</button>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\thref=\"index.jsp\">大盘指数 <span class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"fund.jsp\">基金产品</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"fundBuy.jsp\">基金导购</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"userInfo.jsp\">个人中心</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\"> Dropdown </a>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Action</a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link disabled\" href=\"#\">Disabled</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("\t\t\t<input class=\"form-control mr-sm-2\" type=\"search\"\r\n");
      out.write("\t\t\t\tplaceholder=\"请输入需要查找的内容\" aria-label=\"Search\">\r\n");
      out.write("\t\t\t<button class=\"btn\" type=\"submit\">\r\n");
      out.write("\t\t\t<img src=\"img/search.png\"></button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tclass=\"pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center\">\r\n");
      out.write("\t\t<h1 class=\"display-4\">广东高端制造股票A</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<p class=\"lead\">\r\n");
      out.write("\t\t\t交易状态： <span class=\"redtext\">开放申购 开放赎回</span>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p class=\"lead\">\r\n");
      out.write("\t\t\t购买手续费：\r\n");
      out.write("\t\t\t<del>1.50%</del>\r\n");
      out.write("\t\t\t<span class=\"strongtext\">0.15%</span> <span\r\n");
      out.write("\t\t\t\tclass=\"redtext strongtext\">1</span>折 <a href=\"#\">费率详情>></a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<table class=\"table table-borderless fundPayTable\">\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>基金类型： <a href=\"#\">股票型</a> | 高风险\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>基金规模： 7.34亿元（2020-06-30）</td>\r\n");
      out.write("\t\t\t\t\t\t<td>基金经理： <a href=\"#\">孙迪</a>等\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>成 立 日： 2017-09-01</td>\r\n");
      out.write("\t\t\t\t\t\t<td>管 理 人： <a href=\"#\">广发基金</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td>基金等级： <span class=\"graytext\">暂无评级</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"card-deck mb-3 text-center\">\r\n");
      out.write("\t\t\t<div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"my-0 font-weight-normal\">免费试试</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"card-title pricing-card-title\">\r\n");
      out.write("\t\t\t\t\t\t￥0 <small class=\"text-muted\">/ mo</small>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled mt-3 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<li>新用户限时尝试</li>\r\n");
      out.write("\t\t\t\t\t\t<li>7天收益保留，亏损不陪</li>\r\n");
      out.write("\t\t\t\t\t\t<li>30 users included</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"redtext strongtext\">现在购入还可得基金红包</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-lg btn-block btn-outline-danger\">Sign up\r\n");
      out.write("\t\t\t\t\t\tfor free</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"my-0 font-weight-normal\">立即购买</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"card-title pricing-card-title\">\r\n");
      out.write("\t\t\t\t\t\t￥10 <small class=\"text-muted\">起购</small>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled mt-3 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<li>购买手续费： <del>1.50%</del> <span class=\"strongtext\">0.15%</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"redtext strongtext\">1</span>折\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>Priority email support</li>\r\n");
      out.write("\t\t\t\t\t\t<li>Help center access</li>\r\n");
      out.write("\t\t\t\t\t\t<li>30 users included</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-lg btn-block btn-danger\">Get\r\n");
      out.write("\t\t\t\t\t\tstarted</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"my-0 font-weight-normal\">定投</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"card-title pricing-card-title\">\r\n");
      out.write("\t\t\t\t\t\t￥100 <small class=\"text-muted\">起投</small>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled mt-3 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t<li>免费开启净值估算</li>\r\n");
      out.write("\t\t\t\t\t\t<li>注意：净值估算是按照基金历史定期报告公布的持仓和指数走势预测当天净值，预估数值仅供参考，实际涨跌幅以基金净值为准。</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-lg btn-block btn-danger\">Contact\r\n");
      out.write("\t\t\t\t\t\tus</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" id=\"footer\">\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<p class=\"lead\">联系邮箱 ： jacobon@foxmail.com</p>\r\n");
      out.write("\t<span class=\"text-muted\"><a href=\"https://github.com/ZUFEcsc\">GitHub</a>\r\n");
      out.write("\t\t| <a href=\"https://blog.csdn.net/qq_44702847\">CSDN</a></span>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
