/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-21 02:20:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qrCode_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#footer {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".qrcard {\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\tbackground: url(img/10.jpg) center;\r\n");
      out.write("\tpadding: 18% 5% 10% 60%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bgimg {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=range] {\r\n");
      out.write("\tmargin-top: 8px;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\t-webkit-appearance: none; /*清除系统默认样式*/\r\n");
      out.write("\twidth: 100% !important;\r\n");
      out.write("\tbackground: -webkit-linear-gradient(#ffc107, #ffc107) no-repeat, #ddd;\r\n");
      out.write("\tbackground-size: 33% 100%; /*设置左右宽度比例*/\r\n");
      out.write("\theight: 3px; /*横条的高度*/\r\n");
      out.write("}\r\n");
      out.write("/*拖动块的样式*/\r\n");
      out.write("input[type=range]::-webkit-slider-thumb {\r\n");
      out.write("\t-webkit-appearance: none; /*清除系统默认样式*/\r\n");
      out.write("\theight: 16px; /*拖动块高度*/\r\n");
      out.write("\twidth: 16px; /*拖动块宽度*/\r\n");
      out.write("\tbackground: #f8f9fa; /*拖动块背景*/\r\n");
      out.write("\tborder-radius: 50%; /*外观设置为圆形*/\r\n");
      out.write("\tborder: solid 1px #ddd; /*设置边框*/\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tchangeSpeed();\r\n");
      out.write("\tfunction changeSpeed() {\r\n");
      out.write("\t\tvar value = $('#Qrsize').val();\r\n");
      out.write("\t\tvar valStr = (value - 200) / 3 + \"% 100%\";\r\n");
      out.write("\t\t$('#Qrsize').css({\r\n");
      out.write("\t\t\t\"background-size\" : valStr\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('#Qrsizeinfo').html(value);\r\n");
      out.write("\t\t//document.getElementById('Qrsizeinfo').innerHTML=value;\r\n");
      out.write("\t};\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function changeQrcode() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>QrCodeReq</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<!-- 导航栏 -->\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\"><img\r\n");
      out.write("\t\t\t\tsrc=\"img/psyduck.png\" alt=\"\" width=\"20%\" height=\"20%\"> PsyDuck</a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"success.jsp\">Home <span class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"qrCode.jsp\">QrCode</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\"> Dropdown </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Action</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link disabled\" href=\"#\">Disabled</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control mr-sm-2\" type=\"search\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"qrcard\">\r\n");
      out.write("\t\t\t<div class=\"w-100\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body card\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"card-title\">Online generation of QR Code</h5>\r\n");
      out.write("\t\t\t\t\t<!-- 二维码表单 -->\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"QrCodeServlet\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"staticEmail\" class=\"col-sm-10 col-form-label\">请输入要转换的内容：</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"Qrinfo\" name=\"Qrinfo\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"csnb\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"formControlRange\" class=\"col-sm-10 col-form-label\">请选择要生成二维码的大小：\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"Qrsizeinfo\">300</span>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"Qrsize\" type=\"range\" class=\"form-control-range\"\r\n");
      out.write("\t\t\t\t\t\t\t\tmin=\"200\" max=\"500\" name=\"Qrsize\" value=\"300\" step=\"10\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonchange=\"changeSpeed()\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-warning float-right\">点击生成二维码（跳转页面）</button>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"b1\" class=\"btn btn-warning float-right\">点击生成二维码（本地页面）</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Begin page content -->\r\n");
      out.write("\t\t<div class=\"container float-right\" id=\"footer\">\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<p class=\"lead\">学号：180110910603. &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp桌号：19.</p>\r\n");
      out.write("\t\t\t<p class=\"lead\">姓名：陈彬捷. &nbsp&nbsp&nbsp&nbsp&nbsp班级：18软工2班.</p>\r\n");
      out.write("\t\t\t<p class=\"lead\">If you have any questions, please contact my QQ\r\n");
      out.write("\t\t\t\t879115657.</p>\r\n");
      out.write("\t\t\t<span class=\"text-muted\"><a href=\"https://github.com/ZUFEcsc\">GitHub</a>\r\n");
      out.write("\t\t\t\t| <a href=\"https://blog.csdn.net/qq_44702847\">CSDN</a></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- <p>Back to <a href=\"/docs/4.2/examples/sticky-footer/\">the default sticky footer</a> minus the navbar.</p> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- \r\n");
      out.write("\t<form method=\"post\" action=\"QrCodeServlet\">\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t请输入要转换的内容： <input type=\"text\" name=\"Qrinfo\" value=\"csnb\">\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t请选择要生成二维码的大小： <span id=\"Qrsizeinfo\">300</span> <input id=\"Qrsize\"\r\n");
      out.write("\t\t\t\ttype=\"range\" min=\"200\" max=\"500\" name=\"Qrsize\" value=\"300\" step=\"10\"\r\n");
      out.write("\t\t\t\tonchange=\"document.getElementById('Qrsizeinfo').innerHTML=value\">\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<button>点击生成二维码</button>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
