/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-14 02:00:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".carousel-inner img {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bd-placeholder-img {\r\n");
      out.write("\tfont-size: 1.125rem;\r\n");
      out.write("\ttext-anchor: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 768px) {\r\n");
      out.write("\t.bd-placeholder-img-lg {\r\n");
      out.write("\t\tfont-size: 3.5rem;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logincard {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 20px;\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\tbottom: 400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<title>Res</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 导航栏  -->\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\"><img\r\n");
      out.write("\t\t\t\tsrc=\"img/psyduck.png\" alt=\"\" width=\"20%\" height=\"20%\"> PsyDuck</a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\" href=\"#\">Home\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sr-only\">(current)</span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Link</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\"> Dropdown </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Action</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link disabled\" href=\"#\">Disabled</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control mr-sm-2\" type=\"search\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h2>Sign in</h2>\r\n");
      out.write("\t\t\t<form action=\"RegServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t<!-- 输入用户名信息 -->\r\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"inputEmail3\" class=\"col-sm-2 col-form-label\">Username</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"Username\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"inputEmail3\" placeholder=\"UserName\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 输入密码信息 -->\r\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"inputPassword3\" class=\"col-sm-2 col-form-label\">Password</label>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"Password\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"inputPassword3\" placeholder=\"Password\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 上传头像图片 -->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"exampleFormControlFile1\">Upload your image ：</label> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"file\" class=\"form-control-file\" id=\"exampleFormControlFile1\" name=\"Userimg\" accept=\"image/jpg\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 选择性别信息（单选框组） -->\r\n");
      out.write("\t\t\t\t<fieldset class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<legend class=\"col-form-label col-sm-2 pt-0\">Sex</legend>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-check\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"form-check-input\" type=\"radio\" name=\"sexRadio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"gridRadios1\" value=\"Boy\" checked> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-check-label\" for=\"gridRadios1\">Boy </label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-check\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"form-check-input\" type=\"radio\" name=\"sexRadio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"gridRadios2\" value=\"Girl\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-check-label\" for=\"gridRadios2\">Girl </label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 选择特长信息（复选框） -->\r\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2\">Specialty</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-check\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-check-input\" type=\"checkbox\" name=\"Java\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"gridCheck1\" value=\"Java\" checked> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-check-label\" for=\"gridCheck1\"> Java </label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-check\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-check-input\" type=\"checkbox\" name=\"C++\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"gridCheck2\" value=\"C++\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-check-label\" for=\"gridCheck2\"> C++ </label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-check\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-check-input\" type=\"checkbox\" name=\"Python\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"gridCheck3\" value=\"Python\"> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-check-label\" for=\"gridCheck3\"> Python </label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-check\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-check-input\" type=\"checkbox\" name=\"JavaScript\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"gridCheck4\" value=\"JavaScript\" checked> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-check-label\" for=\"gridCheck4\"> JavaScript </label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 下拉框 -->\r\n");
      out.write("\t\t\t\t<fieldset class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<legend class=\"col-form-label col-sm-2 pt-0\">Major</legend>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-auto my-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"mr-sm-2 sr-only\" for=\"inlineFormCustomSelect\">Preference</label>\r\n");
      out.write("\t\t\t\t\t\t\t<select class=\"custom-select mr-sm-2\" id=\"inlineFormCustomSelect\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"majors\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Computer Major\" selected>Computer Major</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Software Engineering\">Software\r\n");
      out.write("\t\t\t\t\t\t\t\t\tEngineering</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"E-commerce Major\">E-commerce Major</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Information Major\">Information Major</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t<!--\r\n");
      out.write("\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-2\">Major</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-check\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-check-input\" type=\"checkbox\" name=\"majors\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"gridCheck1\" value=\"Computer\" checked> <label\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-check-label\" for=\"gridCheck1\"> Computer </label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-check\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-check-input\" type=\"checkbox\" name=\"majors\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"gridCheck2\" value=\"Software Engineering\" checked> <label\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-check-label\" for=\"gridCheck2\"> Software\r\n");
      out.write("\t\t\t\t\t\t\tEngineering </label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">Sign in</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Begin page content -->\r\n");
      out.write("\t\t<div class=\"container\" id=\"footer\">\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<p class=\"lead\">学号：180110910603.　　　　　　 桌号：19.</p>\r\n");
      out.write("\t\t\t<p class=\"lead\">姓名：陈彬捷.　 　　　　班级：18软工2班.</p>\r\n");
      out.write("\t\t\t<p class=\"lead\">If you have any questions, please contact my QQ\r\n");
      out.write("\t\t\t\t879115657.</p>\r\n");
      out.write("\t\t\t<span class=\"text-muted\"><a href=\"https://github.com/ZUFEcsc\">GitHub</a>\r\n");
      out.write("\t\t\t\t| <a href=\"https://blog.csdn.net/qq_44702847\">CSDN</a></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- <p>Back to <a href=\"/docs/4.2/examples/sticky-footer/\">the default sticky footer</a> minus the navbar.</p> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
